# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays: 
1. A 1-D array called zeros having 10 elements and all the elements are set to zero. 
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. 
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. 
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13 
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [283]:
import numpy as np

In [285]:
# Write your answer here
#A 1-D array called zeros having 10 elements and all the elements are set to zero.
zeros = np.zeros(10)
zeros


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [287]:

ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [356]:
#A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’.
vowels = np.array(['a', 'e', 'i', 'o'  'u'])
vowels

array(['a', 'e', 'i', 'ou'], dtype='<U2')

In [291]:
#A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int.
#ones = np.ones(25).reshape(5,5)
#ones = np.ones(10).reshape(2,5)
ones = np.ones(10,dtype=int).reshape(2,5)
ones 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [293]:

#Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7, 0, -2, 3.4, 10.6, 0, -19 99.9 13
myarray1 =np.array([[2.7, 0, -2],[ 3.4, 10.6, 0],[-19, 99.9 ,13]])
myarray1

array([[  2.7,   0. ,  -2. ],
       [  3.4,  10.6,   0. ],
       [-19. ,  99.9,  13. ]])

In [295]:
#A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float
myarray2 = np.arange(4, 4+15*4 , 4,dtype=float).reshape(3,5)
myarray2 

array([[ 4.,  8., 12., 16., 20.],
       [24., 28., 32., 36., 40.],
       [44., 48., 52., 56., 60.]])

Using the arrays created in Question above, write NumPy commands for the following: 
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2. 
2. Reshape the array ones to have all the 10 elements in a single row. 
3. Display the 2nd and 3rd element of the array vowels. 
4. Display all elements in the 2nd and 3rd row of the array myarray1. 
5. Display the elements in the 1st and 2nd column of the array myarray1. 
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
7. Reverse the array of vowels.

In [298]:
#Write your answer here
q1_zeros=zeros.shape,zeros.size,zeros.ndim,zeros.dtype,zeros.itemsize
q1_zeros


((10,), 10, 1, dtype('float64'), 8)

In [300]:
q1_vowels=vowels.shape,vowels.size,vowels.ndim,vowels.dtype,vowels.itemsize
q1_vowels

((4,), 4, 1, dtype('<U2'), 8)

In [302]:
q1_ones=ones.shape,ones.size,ones.ndim,ones.dtype,ones.itemsize
q1_ones

((2, 5), 10, 2, dtype('int32'), 4)

In [304]:
q1_myarray1=myarray1.shape,myarray1.size,myarray1.ndim,myarray1.dtype,myarray1.itemsize
q1_myarray1

((3, 3), 9, 2, dtype('float64'), 8)

In [306]:
q1_myarray2=myarray2.shape,myarray2.size,myarray2.ndim,myarray2.dtype,myarray2.itemsize
q1_myarray2

((3, 5), 15, 2, dtype('float64'), 8)

In [308]:
#Reshape the array ones to have all the 10 elements in a single row.
q2= ones.reshape(1,10)
q2


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [310]:
#Display the 2nd and 3rd element of the array vowels.
q3=vowels[1:3]
q3

array(['e', 'i'], dtype='<U2')

In [312]:
print(myarray1)

[[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]


In [314]:
#Display all elements in the 2nd and 3rd row of the array myarray1.
q4=myarray1[1:3 , :]
q4

array([[  3.4,  10.6,   0. ],
       [-19. ,  99.9,  13. ]])

In [316]:
#Display the elements in the 1st and 2nd column of the array myarray1.
q5=myarray1[ : , 0:2 ]
q5

array([[  2.7,   0. ],
       [  3.4,  10.6],
       [-19. ,  99.9]])

In [318]:
#Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
q6 = myarray1[ 1:3 ,  0:1 ]
q6

array([[  3.4],
       [-19. ]])

In [320]:
#Reverse the array of vowels.
q7 = vowels[: :-1]
q7

array(['ou', 'i', 'e', 'a'], dtype='<U2')

Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3. 
2. Add the arrays myarray1 and myarray2. 
3. Subtract myarray1 from myarray2 and store the result in a new array. 
4. Multiply myarray1 and myarray2 elementwise. 
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3. 
6. Divide myarray1 by myarray2. 
7. Find the cube of all elements of myarray1 and divide the resulting array by 2. 
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [323]:
# Write your answer here
#Divide all elements of array ones by 3
q1=ones/3
q1




array([[0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333]])

In [325]:
myarray1.shape

(3, 3)

In [327]:
myarray2.shape

(3, 5)

In [329]:
#Add the arrays myarray1 and myarray2.
q2 = myarray1 + myarray2[ : , 0:3 ]
q2 

array([[  6.7,   8. ,  10. ],
       [ 27.4,  38.6,  32. ],
       [ 25. , 147.9,  65. ]])

In [331]:
#Subtract myarray1 from myarray2 and store the result in a new array.
q3c= myarray1 - myarray2[ : , 0:3 ]
q3c

array([[ -1.3,  -8. , -14. ],
       [-20.6, -17.4, -32. ],
       [-63. ,  51.9, -39. ]])

In [333]:
q3c.sort()
q3c

array([[-14. ,  -8. ,  -1.3],
       [-32. , -20.6, -17.4],
       [-63. , -39. ,  51.9]])

In [335]:
#Multiply myarray1 and myarray2 elementwise.
myarray3 = myarray1 * myarray2[ : , 0:3 ]
myarray3

array([[  10.8,    0. ,  -24. ],
       [  81.6,  296.8,    0. ],
       [-836. , 4795.2,  676. ]])

In [337]:
#Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3.
myarray3.sort()
myarray3


array([[ -24. ,    0. ,   10.8],
       [   0. ,   81.6,  296.8],
       [-836. ,  676. , 4795.2]])

In [339]:
q6c = myarray1 / myarray2[ : , 0:3 ]
q6c

array([[ 0.675     ,  0.        , -0.16666667],
       [ 0.14166667,  0.37857143,  0.        ],
       [-0.43181818,  2.08125   ,  0.25      ]])

In [341]:
#Find the cube of all elements of myarray1 and divide the resulting array by 2.
q7c = myarray1**3
q7c/2

array([[ 9.841500e+00,  0.000000e+00, -4.000000e+00],
       [ 1.965200e+01,  5.955080e+02,  0.000000e+00],
       [-3.429500e+03,  4.985015e+05,  1.098500e+03]])

In [343]:

#Find the square root of all elements of myarray2 and divide the resulting array by 2. The result should be rounded to two places of decimals.
q8c =np.round((np.sqrt( myarray2 ))/2,2)
q8c

array([[1.  , 1.41, 1.73, 2.  , 2.24],
       [2.45, 2.65, 2.83, 3.  , 3.16],
       [3.32, 3.46, 3.61, 3.74, 3.87]])

Using the arrays created above, write NumPy commands for the following: 
1. Find the transpose of ones and myarray2. 
2. Sort the array vowels in reverse. 
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [346]:
# Write your answer here
#Find the transpose of ones and myarray2.
#transpose_myarray2 = myarray2.T
#transpose_myarray2
np.transpose (myarray2)


array([[ 4., 24., 44.],
       [ 8., 28., 48.],
       [12., 32., 52.],
       [16., 36., 56.],
       [20., 40., 60.]])

In [376]:
#Sort the array vowels in reverse.
print(vowels)
reversed_arr = np.flip(vowels)
reversed_arr


['a' 'e' 'i' 'ou']


array(['ou', 'i', 'e', 'a'], dtype='<U2')

In [420]:
#Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.
#You can reverse the content in all of the rows and all of the columns with
print(myarray1)
reversed_arr = np.flip(myarray1 )
print('reversed_myarray1'  ,reversed_arr)
#You can easily reverse only the rows with:
reversed_arr_rows = np.flip(myarray1, axis=0)
print('reversed_arr_rows',reversed_arr_rows)
#Or reverse only the columns with:
reversed_arr_columns = np.flip(myarray1, axis=1)
print('reversed_arr_columns',reversed_arr_columns)
#You can also reverse the contents of only one column or row. For example, you can reverse the contents of the row at index position 1 (the second row):
myarray1[1]= np.flip( myarray1[1])
print( 'myarray1[1]',myarray1)
#You can also reverse the column at index position 1 (the second column):
myarray1[:,1] = np.flip(myarray1[:,1])
print('myarray1[:,1]',myarray1)

[[  2.7  99.9  -2. ]
 [  0.   10.6   3.4]
 [-19.    0.   13. ]]
reversed_myarray1 [[ 13.    0.  -19. ]
 [  3.4  10.6   0. ]
 [ -2.   99.9   2.7]]
reversed_arr_rows [[-19.    0.   13. ]
 [  0.   10.6   3.4]
 [  2.7  99.9  -2. ]]
reversed_arr_columns [[ -2.   99.9   2.7]
 [  3.4  10.6   0. ]
 [ 13.    0.  -19. ]]
myarray1[1] [[  2.7  99.9  -2. ]
 [  3.4  10.6   0. ]
 [-19.    0.   13. ]]
myarray1[:,1] [[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]


Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result. 

In [448]:
#Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result.
# Write your answer here


# Create the 2D array myarray4 using arange with a start of -1 and a step of 0.25, and reshape it into 14 rows and 3 columns
myarray4 = np.arange(-1, -1 + 14 * 3 * 0.25, 0.25).reshape(14, 3)

# Print the original array
print("Original array:\n", myarray4)

# Split the array into 3 parts using array_split (to allow uneven splitting)
result = np.array_split(myarray4, 3)

# Print the three parts
print("\nFirst part:\n", result[0])
print("\nSecond part:\n", result[1])
print("\nThird part:\n", result[2])



Original array:
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]
 [ 2.75  3.    3.25]
 [ 3.5   3.75  4.  ]
 [ 4.25  4.5   4.75]
 [ 5.    5.25  5.5 ]
 [ 5.75  6.    6.25]
 [ 6.5   6.75  7.  ]
 [ 7.25  7.5   7.75]
 [ 8.    8.25  8.5 ]
 [ 8.75  9.    9.25]]

First part:
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]]

Second part:
 [[2.75 3.   3.25]
 [3.5  3.75 4.  ]
 [4.25 4.5  4.75]
 [5.   5.25 5.5 ]
 [5.75 6.   6.25]]

Third part:
 [[6.5  6.75 7.  ]
 [7.25 7.5  7.75]
 [8.   8.25 8.5 ]
 [8.75 9.   9.25]]


Using the myarray4 created in the above questions, write commands for the following: 
1. Find the sum of all elements. 
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise. 
4. Find the max of all elements. 
5. Find the min of all elements in each row. 
6. Find the mean of all elements in each row. 
7. Find the standard deviation column wise.

In [454]:
# Write your ansewr here
#Find the sum of all elements.
myarray4.sum()




173.25

In [456]:
#Find the sum of all elements row wise
myarray4.sum(axis=1)

array([-2.25,  0.  ,  2.25,  4.5 ,  6.75,  9.  , 11.25, 13.5 , 15.75,
       18.  , 20.25, 22.5 , 24.75, 27.  ])

In [472]:
np.sum(myarray4,axis=1)

array([-2.25,  0.  ,  2.25,  4.5 ,  6.75,  9.  , 11.25, 13.5 , 15.75,
       18.  , 20.25, 22.5 , 24.75, 27.  ])

In [458]:
#Find the sum of all elements column wise.
myarray4.sum(axis=0)


array([54.25, 57.75, 61.25])

In [460]:
#Find the max of all elements.
myarray4.max()

9.25

In [462]:
#Find the min of all elements in each row.
myarray4. min()

-1.0

In [468]:
#Find the mean of all elements in each row
myarray4. mean(axis=1)

array([-0.75,  0.  ,  0.75,  1.5 ,  2.25,  3.  ,  3.75,  4.5 ,  5.25,
        6.  ,  6.75,  7.5 ,  8.25,  9.  ])

In [470]:
#Find the standard deviation column wise.
myarray4.std(axis=0)

array([3.02334666, 3.02334666, 3.02334666])

#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [496]:
# Write your answer here
import pandas as pd
capitals = pd.read_csv('country-capital-lat-long-population.csv')
capitals.head()


Country           Capital City  Latitude  Longitude  Population  \
0     Afghanistan                  Kabul   34.5289    69.1725     4011770   
1         Albania        Tiranë (Tirana)   41.3275    19.8189      475577   
2         Algeria  El Djazaïr  (Algiers)   36.7525     3.0420     2693542   
3  American Samoa              Pago Pago  -14.2781  -170.7025       48526   
4         Andorra       Andorra la Vella   42.5078     1.5211       22614   

  Capital Type  
0      Capital  
1      Capital  
2      Capital  
3      Capital  
4      Capital

In [498]:
capitals.tail()

Country Capital City  Latitude  Longitude  Population  \
229  Wallis and Futuna Islands     Matu-Utu  -13.2816  -176.1745        1025   
230             Western Sahara     El Aaiún   27.1532   -13.2014      232388   
231                      Yemen      Sana'a'   15.3531    44.2078     2779317   
232                     Zambia       Lusaka  -15.4134    28.2771     2523844   
233                   Zimbabwe       Harare  -17.8294    31.0539     1515016   

    Capital Type  
229      Capital  
230      Capital  
231      Capital  
232      Capital  
233      Capital

In [500]:
capitals.max()

Country                   Zimbabwe
Capital City                Zagreb
Latitude                   64.1835
Longitude                 179.1991
Population                37468302
Capital Type    Seat of Government
dtype: object

In [502]:
capitals.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       234 non-null    object 
 1   Capital City  234 non-null    object 
 2   Latitude      234 non-null    float64
 3   Longitude     234 non-null    float64
 4   Population    234 non-null    int64  
 5   Capital Type  234 non-null    object 
dtypes: float64(2), int64(1), object(3)
memory usage: 11.1+ KB


In [510]:
#Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
numpy_array = pd.DataFrame(capitals)
numpy_array = numpy_array .to_numpy()
numpy_array 

array([['Afghanistan', 'Kabul', 34.5289, 69.1725, 4011770, 'Capital'],
       ['Albania', 'Tiranë (Tirana)', 41.3275, 19.8189, 475577,
        'Capital'],
       ['Algeria', 'El Djazaïr  (Algiers)', 36.7525, 3.042, 2693542,
        'Capital'],
       ...,
       ['Yemen', "Sana'a'", 15.3531, 44.2078, 2779317, 'Capital'],
       ['Zambia', 'Lusaka', -15.4134, 28.2771, 2523844, 'Capital'],
       ['Zimbabwe', 'Harare', -17.8294, 31.0539, 1515016, 'Capital']],
      dtype=object)

In [514]:
#Use broadcasting to compute the euclidean distance of capital cities from Riyadh.
capitals = pd.DataFrame(capitals)

# Step 2: Coordinates of Riyadh (Saudi Arabia)
riyadh_coordinates = np.array([24.7136, 46.6753])

# Step 3: Extract the coordinates (Latitude, Longitude) of all other capital cities
capital_coordinates = capitals[['Latitude', 'Longitude']].to_numpy()

# Step 4: Compute the Euclidean distances using broadcasting
# Distance = sqrt((x2 - x1)^2 + (y2 - y1)^2)
distances = np.sqrt(np.sum((capital_coordinates - riyadh_coordinates) ** 2, axis=1))

# Step 5: Add the distances to the DataFrame
capitals['Distance from Riyadh'] = distances

# Step 6: Print the DataFrame with the distances
print(capitals[['Country', 'Capital City', 'Distance from Riyadh']])

                       Country           Capital City  Distance from Riyadh
0                  Afghanistan                  Kabul             24.545145
1                      Albania        Tiranë (Tirana)             31.579865
2                      Algeria  El Djazaïr  (Algiers)             45.263672
3               American Samoa              Pago Pago            220.847143
4                      Andorra       Andorra la Vella             48.533858
..                         ...                    ...                   ...
229  Wallis and Futuna Islands               Matu-Utu            226.065629
230             Western Sahara               El Aaiún             59.926379
231                      Yemen                Sana'a'              9.680264
232                     Zambia                 Lusaka             44.143741
233                   Zimbabwe                 Harare             45.320360

[234 rows x 3 columns]


#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [516]:
# Write your answer here
capitals = pd.DataFrame(capitals)

# Step 2: Coordinates of Washington, D.C. (USA)
washington_dc_coordinates = np.array([38.8951, -77.0369])

# Step 3: Extract the coordinates (Latitude, Longitude) of all other capital cities
capital_coordinates = capitals[['Latitude', 'Longitude']].to_numpy()

# Step 4: Compute the Euclidean distances using broadcasting
distances = np.sqrt(np.sum((capital_coordinates - washington_dc_coordinates) ** 2, axis=1))

# Step 5: Add the distances to the DataFrame
capitals['Distance from Washington, D.C.'] = distances

# Step 6: Sort the DataFrame by the distance and get the top 10 closest cities
closest_capitals = capitals[capitals['Capital City'] != 'Washington, D.C.'].sort_values('Distance from Washington, D.C.').head(10)

# Step 7: Print the names of the countries of the top 10 closest capital cities
print(closest_capitals[['Country', 'Capital City', 'Distance from Washington, D.C.']])





                       Country        Capital City  \
36                      Canada     Ottawa-Gatineau   
14                     Bahamas              Nassau   
22                     Bermuda            Hamilton   
55                        Cuba  La Habana (Havana)   
215   Turks and Caicos Islands       Cockburn Town   
38              Cayman Islands         George Town   
94                       Haiti      Port-au-Prince   
107                    Jamaica            Kingston   
64          Dominican Republic       Santo Domingo   
177  Saint Pierre and Miquelon        Saint-Pierre   

     Distance from Washington, D.C.  
36                         6.657523  
14                        13.840288  
22                        13.924373  
55                        16.655397  
215                       18.403584  
38                        20.082509  
94                        20.891877  
107                       20.899516  
64                        21.616986  
177                      

In [520]:
#Create and print a NumPy array containing the coordinates of the top 10 cities.
capitals = pd.DataFrame(capitals)

# Step 2: Coordinates of Washington, D.C. (USA)
washington_dc_coordinates = np.array([38.8951, -77.0369])

# Step 3: Extract the coordinates (Latitude, Longitude) of all other capital cities
capital_coordinates = capitals[['Latitude', 'Longitude']].to_numpy()

# Step 4: Compute the Euclidean distances using broadcasting
distances = np.sqrt(np.sum((capital_coordinates - washington_dc_coordinates) ** 2, axis=1))

# Step 5: Add the distances to the DataFrame
capitals['Distance from Washington, D.C.'] = distances

# Step 6: Sort the DataFrame by the distance and get the top 10 closest cities
closest_capitals = capitals[capitals['Capital City'] != 'Washington, D.C.'].sort_values('Distance from Washington, D.C.').head(10)

# Step 7: Create a NumPy array with the coordinates of the top 10 closest capital cities
closest_coordinates = closest_capitals[['Latitude', 'Longitude']].to_numpy()

# Step 8: Print the NumPy array
print("Coordinates of the top 10 closest cities to Washington, D.C.:")
print(closest_coordinates)

Coordinates of the top 10 closest cities to Washington, D.C.:
[[ 45.4166 -75.698 ]
 [ 25.0582 -77.3431]
 [ 32.2915 -64.778 ]
 [ 23.1195 -82.3785]
 [ 21.4612 -71.1419]
 [ 19.2866 -81.3744]
 [ 18.5392 -72.335 ]
 [ 17.997  -76.7936]
 [ 18.4896 -69.9018]
 [ 46.7738 -56.1815]]
